env:
  browser: true
  es2020: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:meteor/recommended'
  - 'plugin:react/recommended'
globals:
  Meteor: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - coffeescript
  - meteor
  - react
rules:
  indent: off  # incompatible with CoffeeScript
    #- error
    #- 2
  linebreak-style:
    - error
    - unix
  no-useless-escape: off  # incompatible with CoffeeScript's ///
  quotes:
    - error
    - single
  semi:
    - error
    - always
  react/no-unescaped-entities:
    - warn
    - forbid: ['>', '"', '}']
  meteor/no-session: off
  meteor/audit-argument-checks:
    - error
    - checkEquivalents:
      - checkId
      - checkMeeting
settings:
  react:
    version: detect
